### ISSUE TITLE
Broken segment metadata with Druid v0.9.1?

### ISSUE THREAD

**Issue by cdeszaq** [yahoo/fili#63]
Some people are seeing errors from their `SegmentMetadataLoader` that seem to indicate there's been a new field added to the Segment Metadata info returned by Druid's coordinator. 

I _think_ we can just tell Jackson to ignore unknown properties when it deserializes into the `NumberedShardSpec` class, but we should investigate what the meaning of the new field is in case we should be paying attention to it.

If we can ignore it, here's some articles on how to do that:
- http://stackoverflow.com/a/7546047/20770
- http://stackoverflow.com/a/26371693/20770
- http://www.baeldung.com/jackson-deserialize-json-unknown-properties
- http://javaninja.net/2015/02/jackson2-dreaded-com-fasterxml-jackson-databind-exc-unrecognizedpropertyexception/

Here's what the errors look like:

```
2016-10-12 22:12:40.323	ERROR	[AsyncHttpClient-4-43]	6a954a8f-5e85-4a18-af15-d14d709e7bb1	c.y.b.webservice.application.Loader - DataSourceMetadataLoader: Async request to druid failed:
java.lang.UnsupportedOperationException: Unable to read metadata for: 'monthly_data'.
	at com.yahoo.bard.webservice.metadata.DataSourceMetadataLoader$1.invoke(DataSourceMetadataLoader.java:177)
	at com.yahoo.bard.webservice.druid.client.impl.AsyncDruidWebServiceImpl$1.onCompleted(AsyncDruidWebServiceImpl.java:187)
	at com.yahoo.bard.webservice.druid.client.impl.AsyncDruidWebServiceImpl$1.onCompleted(AsyncDruidWebServiceImpl.java:144)
	at org.asynchttpclient.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:64)
	at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:188)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:223)
	at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:189)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "partitionDimensions" (class com.yahoo.bard.webservice.druid.model.metadata.NumberedShardSpec), not marked as ignorable (3 known properties: "partitions", "type", "partitionNum"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.yahoo.bard.webservice.metadata.DataSourceMetadata["segments"]->java.util.ArrayList[0]->io.druid.timeline.DataSegment["shardSpec"]->com.yahoo.bard.webservice.druid.model.metadata.NumberedShardSpec["partitionDimensions"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:836)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1306)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:451)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:134)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:122)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:518)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:376)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:376)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3703)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2006)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2477)
	at com.yahoo.bard.webservice.metadata.DataSourceMetadataLoader$1.invoke(DataSourceMetadataLoader.java:174)
	... 32 common frames omitted
```

**Comment by archolewa** [comment]
Closing this issue, since it has been addressed by #66
